return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "black",
        "docker-compose-language-service",
        "dockerfile-language-server ",
        "eslint-lsp",
        "gofumpt",
        "golangci-lint",
        "gopls",
        "hadolint",
        "isort",
        "json-lsp",
        "lua-language-server",
        "markdown-toc",
        "markdownlint-cli2",
        "marksman",
        "prettierd",
        "pyright",
        "rubocop",
        "ruff",
        "shellcheck",
        "shfmt",
        "standardrb",
        "stylua",
        "tailwindcss-language-server",
        "terraform-ls",
        "tflint",
        "typescript-language-server",
      },
    },
  },
}
